[platformio]
default_envs = m5stack-cardputer-legacy

; Placa oficial recomendada pela M5Stack:
[env:m5stack-cardputer]
platform = espressif32
board = m5stack-cardputer
framework = arduino

[env:m5stack-cardputer-legacy]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.flash_mode = qio
board_upload.speed = 921600
board_build.arduino.partitions = no_ota_3MB.csv
build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
